### PR TITLE
Upgrade tarball to 5.8 to fix compilation

### PR DESCRIPTION
**Pull request by thibaultduponchelle**
Hello :smile: 

First thank you again for having merged quickly my previous PR :+1: 

This module is fixed concerning ABMB prerequisite but I have a compilation issue right now. You can see it [here](https://github.com/thibaultduponchelle/aliens-ci/runs/637892892?check_suite_focus=true) -> compiling keytool.c 
```
keytools.c:155:25: error: dereferencing pointer to incomplete type 'EVP_MD_CTX {aka struct evp_md_ctx_st}'
```
I propose to upgrade to 5.8 to fix this.

Best regards.

Thibault

### CODE REVIEW

**Comment by ollyg** [comment]
Hi @thibaultduponchelle 
Well, this distribution (MAXTC) exists only because at the time 5.8 was not released, and the default number of textual conventions prior to 5.8 was not 16k. Since 5.8 the default is 16k so moving to using 5.8 makes this distribution redundant.
I guess what I'm saying is that this distribution should probably be deprecated. There are three options:

- just delete it from the CPAN
- leave it on the CPAN with a DEPRECATED notice (fails to build)
- delete it from CPAN and include a dummy MAXTC package in Alien::SNMP so that people can still depend on the package via cpanm and it will be installed and work (this would require a patch)

I like the third option but don't have the time right now. Your thoughts?

**Comment by ollyg** [comment]
By the way would you like a commit bit on this repo and the Alien::SNMP one?

**Comment by plicease** [comment]
Just my 0.02c but deleting from CPAN is probably fine.  There aren't any reverse deps on this, and although it is possible there are darkpan deps, there is always backpan and metacpan search to find and switch to Alien::SNMP.

If someone does add a dummy wrapper around Alien::SNMP with the name Alien::SNMP::MAXTC, keep in mind that the dist_dir is computed from the class name:

https://github.com/Perl5-Alien/Alien-Build/blob/f395c977038d3b0ce1c23261a3fa10c1265bcd33/lib/Alien/Base.pm#L202

This is technically incorrect, but it has worked .  And it looks like the only way to override it is to override the private _dist_dir method which is icky.  To fix this correctly we'd want a public dist_name method on `Alien::Base`.  A PR against AB to do that would be reasonable, but it is also sounding like more effort than it is worth.

**Comment by thibaultduponchelle** [comment]
Hello @ollyg,

My first idea was also to remove the CPAN module. 

Concerning commit bit, I haven't planned to do much than some maintenance on your modules. Maybe a migration to alienfile could be considered, but that's about all I guess (?).
And honestly the current Alien::SNMP implementation seems very clean then there is no hurry to change anything.
No problem to have the commit bit anyway, It should not hurt as I'm a respectful and careful person with both people and code ;) 
I could apply from time to time small fixes if needed or I can pull request like we have done recently.
Thus I let you decide.

Best regards.

Thibault

**Comment by thibaultduponchelle** [comment]
Hello :smiley: 

What is your opinion/decision ?

Rgds.

Thibault

**Comment by inphobia** [comment]
while trying to import ciscoucs mibs i ran into the problem that i overran the max_imports (256 by default), so i rigged this module temporarily to get over that. code is crude but working:
https://github.com/inphobia/Alien-SNMP-MAXTC/tree/nn_maximports_58

gotchas:
 * this needs to be patched in net-snmp source, so some kind of alien module will still be needed
 * net-snmp 5.9 does away with index files which breaks most op netdisco/netdisco-mibs scripts

hack to setmaxtc (not pretty, was mostly for testing):
https://github.com/inphobia/netdisco-mibs/commit/be6e7aac4099f176be7775acad36eca599e1a54d#diff-02f7858b201b138addbe05e1dfabc8b5d25d0c439e48c8357c2257934701304d

so perhaps a::s::maxtc needs to be retired, but then a new module would be needed for max_imports or a::s would need to get that patch added.

**Pull request closed without merging**
